apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: discuss-locationservice
  name: discuss-locationservice
spec:
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  selector:
    service: discuss-locationservice
status:
  loadBalancer: {}
